import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import { Poppins } from 'next/font/google'
import SideNav from '@/components/ui/main-side-nav'
import NavItem from '@/components/ui/side-nav-item';
import { IoBagHandle} from "react-icons/io5";
import { FaPenSquare, FaImages, FaUserAlt } from "react-icons/fa";
import { FaHouse} from "react-icons/fa6";
import { BsFillChatDotsFill, BsGearFill, BsGridFill} from "react-icons/bs";

const inter = Inter({ subsets: ['latin'] })

// Configura a fonte para usar as propriedades padrões
const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} transition-colors ease-in duration-200 pl-20 bg-indigo-200 dark:bg-slate-950 ${poppins.className}`}>
        <SideNav>
          <NavItem name="Home">
              <FaHouse size="1.2em"/>
          </NavItem>
          <NavItem name="Posts">
              <FaPenSquare size="1.2em"/>
          </NavItem>
          <NavItem name="Meus Packs">
              <FaImages size="1.2em"/>
          </NavItem>
          <NavItem name="Comentários" badge={1}>
              <BsFillChatDotsFill size="1.2em"/>
          </NavItem>
          <NavItem name="Loja de Packs">
              <IoBagHandle size="1.2em"/>
          </NavItem>
          <NavItem name="Perfil">
              <FaUserAlt size="1.2em"/>
          </NavItem>
          <NavItem name="Configurações">
              <BsGearFill size="1.2em"/>
          </NavItem>
          <NavItem name="Ferramentas">
              <BsGridFill size="1.2em"/>
          </NavItem>
        </SideNav>
        {children}
      </body>
    </html>
  )
}
